config/routes.rb
Connectfour::Application.routes.draw do
  get "connect/index"

  root 'connect#index'

  get "connect/play", :as => 'plays'
  

  

end

app/models/board.rb
class Board
	attr_accessor :rows, :cols, :cells
	def initialize (rows, cols)
		@rows = rows
		@cols = cols
		@cells = []
		(0...rows)
		for x in 0...rows do
			for y in 0...cols do
				cells << Cell.new(x, y)
			end	
		end
	end
end

app/models/cell.rb
class Cell 
	attr_accessor :x, :y, :played
	def initialize(x, y)
		@x = x
		@y = y
	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/connect_controller.rb
class ConnectController < ApplicationController
  def index
  end

  def play
  		@board = Board.new(6,7)
  end	
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/connect_helper.rb
module ConnectHelper
end

app/views/connect/index.html.erb
<header>
	<h1>Connect Four Sample App</h1>
</header>

<div>
	<p>Connect Four (also known as Captain's Mistress, Four Up, Plot Four, Find Four, Fourplay, Four in a Row and Four in a Line) is a two-player game in which the players first choose a color and then take turns dropping colored discs from the top into a seven-column, six-row vertically suspended grid. </p>
</div>

<%= link_to "Play", plays_path %>

app/views/connect/play.html.erb
<div class="pure-g-r">
  <div class="pure-u-1" id="layout">
    <h1>Connect Four</h1>
    <h3>Sample App</h3>
    <table id="tallyboard" class="pure-table">
      <thead>
        <tr>
          <td id="playerCellA">
            Player A
          </td>
          <td id="playerCellB">
            Player B
          </td>
        <tr/>
      </thead>
      <tr>
        <td id="turnCell" colspan="2">
          <h1>TURN</h1>
        </td>
      <tr/>
    </table>
    <hr/>

    <table id = "board" class="pure-table pure-table-bordered">
      <tr class = "0">
        <% (@board.cells). each do |cell| %>

          <td class = "<%= cell.y %>" >
            <button
              class = "cellButton"
              id = "<%= cell.x %>_<%= cell.y %>"
              onclick = "play(<%= cell.x %>, <%= cell.y %>)">
              0
              <input type = "hidden"
                id = "played_<%= cell.x %>_<%= cell.y %>"
                value = "<%= cell.played %>" />
            </button>
          </td>

          <% if cell.y == (@board.cols - 1)  %>
            </tr>
            <% if cell.x != (@board.rows - 1)  %>
              <tr class = "<%= cell.x + 1 %>">
            <% end %>
          <% end %>
        <% end %>
    </table>

    <input type="hidden" id="clicks" value="0"/>
    <hr/>

  </div>

</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Connectfour</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>